### ISSUE TITLE
Funding Status choices need more work

### ISSUE THREAD

**Issue by jayfk** [jayfk/fundingoss.com#1]
Currently, we have:
- Well Funded
- Self Funded
- No Funding
- Unknown

**Comment by jayfk** [comment]
The code lives here, if someone want's to tackle it https://github.com/jayfk/fundingoss.com/blob/master/funding/projects/models.py#L10-L15

**Comment by nayafia** [comment]
Been thinking about how to break this up. Could have two questions around funding:

**Status:** (radio buttons)
- Well funded
- Somewhat funded
- Not funded
- Unknown

(I'd remove "self funded" because that basically means "no funding")

**Type of funding:** (checkboxes)
- Corporate
- Individual
- Foundation
- Academia
- Consulting/Services
- No funding

What do you think?  @techtonik

Also what happens to the current funding categories if we change them? Do they get wiped? I don't mind redoing them if so.

**Comment by jayfk** [comment]
> Also what happens to the current funding categories if we change them? Do they get wiped? I don't mind redoing them if so.

We can migrate them, thanks to Django's data migration.

**Comment by nayafia** [comment]
ok, cool :)

**Comment by techtonik** [comment]
I think that keeping it simple to save people time on entering the data is a good thing, so modifying **Status** radio `s/Self Funded/Somewhat Funded/` and leaving 4 choices is fine.

As for **types of funding**, I do not believe that these types do really exist. I just wrote a 3kB+ text about it in this comment, but it looks like not the best place for longreads, and writing summary turned it into another 2kB+ test, so I just leave it as is - the idea to have those checkboxes is good enough. =)

@nayafia need a place to work on the causes - perhaps that will help to improve the questionaire.

**Comment by techtonik** [comment]
@nayafia #13 "Somewhat funded" is also about the **capacity** - I am not sure if there is a methodology to calculate that (only ideas), but it is interesting to know for example, what people think about it.

**Comment by techtonik** [comment]
@jayfk is it possible to make a aggregate for those checkboxes and radios to count every vote? So that later we can have the data how many people think that project is well funded and how many people think it is insufficiently funded?

**Comment by jayfk** [comment]
@techtonik That would be possible from a technical side, but I'm not quite sure if that's really needed.

From my point of view it makes more sense to restrict the access to the funding status to the group of maintainers the project has.

**Comment by techtonik** [comment]
I am not sure that there is consensus even within maintainers, and with that data it looks like there is. =) So maybe we should add options **Other** or **No consensus** then.

**Comment by jayfk** [comment]
> I am not sure that there is consensus even within maintainers, and with that data it looks like there is. =) So maybe we should add options Other or No consensus then.

That's a good point, haven't thought about that one =)

For now, @nayafia suggestion with your addition seems to be the easiest solution that covers a lot of use cases. What do you think?

**Comment by jayfk** [comment]
As a sidenote: Django's admin interface has a lot of goodies like bulk editing of fields in the list view. If that makes editing easier for you @nayafia, just let me know and I'll add them.

**Comment by nayafia** [comment]
@jayfk yep I think that makes sense as an easy 90% solution. And yeah if it's easy to add those features, they're not a must have, but I'd appreciate them! :)

**Comment by jayfk** [comment]
I've worked on this. 

The `Add Project` page now has ne choices you suggested:

![screen shot 2016-02-04 at 12 04 45](https://cloud.githubusercontent.com/assets/2930472/12813317/9056d7a2-cb37-11e5-8757-5e96f9052c24.png)

And the admin interface is now list editable and has a search field:

![screen shot 2016-02-04 at 12 07 54](https://cloud.githubusercontent.com/assets/2930472/12813398/089b0ec2-cb38-11e5-9407-89cccd35de62.png)

I haven't found a good way to display the `funding_type` checkboxes in the listview (they were displayed as a comma separated `TextField`), so they have to be edited on the detail page.

**Comment by nayafia** [comment]
Thanks for doing this! Looks great. Think it takes care of this issue for now.
