### ISSUE TITLE
Add some documentation / explainations to README.md

### ISSUE THREAD

**Issue by vhf** [jayfk/fundingoss.com#11]
README.md could have a small section leaving no doubt about the following things:
- How does it work?
- Does it poll the original spreadsheet every once in a while?
- Is it somehow kept in sync with the original spreadsheet?
- How can I modify a project I maintain?

**Comment by jayfk** [comment]
Yes, this needs to be addressed. I'm about to got, so in short:

> How does it work?

Magic! No, that's just a simple Django app that runs on docker/

> Does it poll the original spreadsheet every once in a while?
> Is it somehow kept in sync with the original spreadsheet?

Not automated, but I plan to add this functionality (at least semi automated).

> How can I modify a project I maintain?

The best way is to open an issue here.

**Comment by nayafia** [comment]
thanks for these suggestions - added info to the readme!
