### ISSUE TITLE
cookiecutter updates

### ISSUE THREAD

**Issue by pydanny** [jayfk/fundingoss.com#14]
- Change 'Unknown' status to 'No Funding'
- Change description to `An extendable command-line utility that works everywhere on all maintained Python versions that creates projects from cookiecutters (project templates). E.g. Python package projects, jQuery plugin projects, LaTeX projcts.`
- Change needs to 'Funding to allow maintainers the time needed to add functionality, ensure cross platform stability, and support the necessary time and effort in evaluating pull requests'.

**Comment by jayfk** [comment]
Fixed, http://fundingoss.com/38/
