### ISSUE TITLE
Flesh out CONTRIBUTING.md

### ISSUE THREAD

**Issue by tnorthcutt** [jayfk/fundingoss.com#23]
https://github.com/jayfk/fundingoss.com/commit/bf36251503da9bcf672e8ab31e11d52bfdf98f9a added a CONTRIBUTING.md file, but it could use some more information on _how_ to contribute, e.g. "add the project's info files x, y, and z, then submit a pull request".

An easy way to do this would be to link to a well-formatted PR, once one exists :smile:

**Comment by jayfk** [comment]
I've added some instructions in https://github.com/jayfk/fundingoss.com/commit/596cd6a5539f1a758aa84994ccf28b11b8c1a9f4 and linked to it from README.md in https://github.com/jayfk/fundingoss.com/commit/1502fac82b7ae57abd7ab0c0208bdc172dd8ce2b
