### ISSUE TITLE
pip's needs are innacurately described

### ISSUE THREAD

**Issue by pydanny** [jayfk/fundingoss.com#36]
http://fundingoss.com/71/

pip has at least one person, @dstufft, maintaining it as part of their full time job. It has regular maintenance, with commits happening every day.

**Comment by nayafia** [comment]
I can edit this. would you call it "somewhat funded" or "well funded"? any other needs that should be added?

**Comment by dstufft** [comment]
Pip itself has no funding. I (via my work at HPE) am tasked full time on upstream python packaging work. So I split my time between pip, virtualenv, PyPI/Warehouse, standards process and other misc things. How exactly that is represented here, I don't know. Could be somewhat funded or fully funded I dunno.

**Comment by techtonik** [comment]
@nayafia s/clear lack of maintenance/needs more help/

Aside note. Look like 'Funding' status needs more quality metrics. It is not like "how project is funded", but more like "how project maintainers are supported".

`pip`:
- 1 "secured maintainer" (good)
- bus factor if 1 (critical)
- 116 open pull requests (bad)
- 520 open issues (so-so)
- has ??? contributors with unknown status

"secured maintainer" means that person is either maintaining the project as a part of job OR (has other funding AND interest to keep it going).

**Comment by jayfk** [comment]
Would it help to split `somewhat funded` into parts?
- bare minimum
- could be better
- okay

Again, not looking for the holy grail here. But maybe that's something that helps while we iterate on ideas how to describe this appropriately.

**Comment by pydanny** [comment]
The number of pull requests that are open have nothing to do with the health of a project. Instead, it has everything to do with how many people are submitting pull requests compared to how fast those with commit rights want to accept/discard them. The same goes for issues. My statement is proven by other projects such as Django, Rails, Linux, Open Stack, and every other immensely popular open source project on the planet.

Furthermore, it is up to a project's maintainers to report the projects bus factor, not to mention any statements on the organizational structure. Having third-party observers determine a bus factor for a project listed on fundingoss.com not only introduces bias, it encourages counterproductive project trolling.

**Comment by nayafia** [comment]
I'm leaning towards simplicity for this project. When I think of funding, what I mean is support, so if someone is being paid to work on pip, that counts as funding. We could call it "Support status" (well supported, somewhat supported, etc) instead of funding? But I don't want these terms to get too granular and confusing, either.

For now, I've edited pip to call it "somewhat funded", and added a bit of explanation about @dstufft's role on the project.

**Comment by dstufft** [comment]
Seems reasonable to me.

**Comment by techtonik** [comment]
> Furthermore, it is up to a project's maintainers to report the projects bus factor, not to mention any statements on the organizational structure.

Nobody objects that, but if project maintainers are reluctant, or don't want to admit that things could be better, somebody needs to do it for them.

> Having third-party observers determine a bus factor for a project listed on fundingoss.com not only introduces bias, it encourages counterproductive project trolling.

/me added `counterproductive project trolling` to his phrasebook
