### ISSUE TITLE
Standard license identifiers

### ISSUE THREAD

**Issue by mlinksva** [jayfk/fundingoss.com#44]
I notice in https://github.com/jayfk/fundingoss.com/blob/9130a722557f796a841d624b5c03bc145ad2a6f0/funding/projects/models.py#L24

```
    LICENSE_CHOICES = (
        ("apache_2", "Apache 2.0"),
        ("bsd_3", "BSD 3-Clause (New)"),
        ("bsd_2", "BSD 2-Clause (FreeBSD)"),
        ("cddl1", "Common Development and Distribution License 1.0"),
        ("gagpl3", "GNU Affero General Public License 3"),
        ("gpl", "GPL"),
        ("lgpl", "LGPL"),
        ("mit", "MIT"),
        ("mpl", "Mozilla Public License 2.0"),
        ("epl", "Eclipse Public License"),
        ("unknown", "Unknown"),
        ("other", "Other")
    )
```

It'd be nice to use [SPDX license identifiers](http://spdx.org/licenses/) so that the licenses are unambiguous and others may easily cross-reference.

Just a very minor quibble. For community education purposes, I like to see prominent projects not inventing yet another license list and naming scheme. :smile: 

I realize from https://github.com/jayfk/fundingoss.com/issues/40#issuecomment-182124127 not at all a priority for this project, though this would be more feasible than pulling from a meta repository for open source projects which may or may not exist in adequate form to pull from.

**Comment by jayfk** [comment]
Interesting, I wasn't aware that there are identifiers around (but makes sense when I think about it). I used https://opensource.org/licenses as a reference and included the more popular licences. 

If you have the time, just edit them and send a pull request so that we have that covered.
