### ISSUE TITLE
Change default "type of funding" to unknown

### ISSUE THREAD

**Issue by nayafia** [jayfk/fundingoss.com#52]
The "type of funding" label currently reads "no funding" if no type of funding is checked, which leads to confusion (ex. Docker had "well funded" label, but said "no funding" under Type of Funding).

If Type of Funding isn't specified, the default label should read "unknown" to make it clear that no box was checked, not that there is no funding.

**Comment by techtonik** [comment]
As I see it on http://fundingoss.com/create/ it is impossible to skip selection of funding status, so maybe it is just a single mistake with Docker? http://fundingoss.com/22/

**Comment by jayfk** [comment]
Right! I think the problem in this case was that the `Type of funding` was introduced after Docker was added.

It now defaults to `unknown`.

**Comment by nayafia** [comment]
yes, that is what I meant 😉 thank you!
