### ISSUE TITLE
Project edit: Muse protocol

### ISSUE THREAD

**Issue by Badg** [jayfk/fundingoss.com#88]
In the past (however many weeks it's been) there have been a bunch of branding changes with the [Muse protocol](http://fundingoss.com/47/) entry. Per the readme, I should open an issue or ping @nayafia -- porque no los dos? Anyways, changes follow:
- "Muse protocol" -> "Golix protocol"
- Status -> [Prototype python implementation](https://github.com/Muterra/py_golix) and [WIP cross-language-accessible application](https://github.com/Muterra/py_hypergolix)
- Function -> "Effortless end-to-end encryption for IoT development"
- Website -> [https://github.com/Muterra/doc-golix](https://github.com/Muterra/doc-golix)

Thanks!

**Comment by nayafia** [comment]
All updated! 👍
